apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: weatherapp-hpa
  labels:
    app: weatherapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: weatherapp-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Object
    object:
      metricName: http_request
      target:
        kind: Service
        name: weatherapp-service
      targetValue: 2
